name: "APIsec|SCAN - Dynamic API Security Testing"

on:
  workflow_dispatch:
  # push:
  #   branches: ["main"]

jobs:
  test_scan:
    permissions:
      contents: read # to checkout repository code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: APISec|SCAN Testing
        uses: turnitin-actions/free-API-security-test-action@main
        with:
          base_url: "http://crapi.apisec.ai"
          specification_path: "https://gist.githubusercontent.com/ManuelBerrueta/11923a4a4210a828706ff51f19633a72/raw/c3999b1d7750d2fbf7c931d9a29dfab0e0c7c2bb/crapi_spec.json"
